### ISSUE TITLE
No documentation on what variables are able to be used for templates.

### ISSUE THREAD

**Issue by ghost** [hemantsharma-io/MockingBird#10]
There is no documentation on what variables there are. Please add it somewhere.  How am I supposed to get the body of the request in the same format that fiddler show it when I drag a session to the Composer tab?

**Comment by hemantsharma-io** [comment]
> There is no documentation on what variables there are. Please add it somewhere. How am I supposed to get the body of the request in the same format that fiddler show it when I drag a session to the Composer tab?

@stackedUI you didn't mention what are you trying to achieve by getting a Composer like request body.

MockingBird is an extension and like any other extension it extends existing functionality. [This method shows](https://github.com/hemantsharma-io/MockingBird/blob/master/code/MockingBird/Domain/Session.cs#L30) how to get the request body as HTML encoded string. Each selected session in this extension inherits from Fiddler.Session class, which means you can use all the properties exposed by this class. e.g. [this default template ](https://github.com/hemantsharma-io/MockingBird/blob/master/code/MockingBird/templates/Default%20Mocking%20Bird.tpl#L2) example is looping through all the `RequestHeaders` of session class instance.

In addition to above, please note that the request body is a binary data and the consumer of this data would need to decide how to parse it either by knowing what exactly the content type will be or having a switch case on request header's content type.

Documenting Fiddler classes is beyond the scope of this extension and you can explore [https://www.telerik.com/fiddler](https://www.telerik.com/fiddler) for more details. You can look at [Telerik FiddlerScript Editor](https://www.telerik.com/download/fiddler/fiddlerscript-editor) to find out all the properties each object has

**Comment by ghost** [comment]
I would like to have the body in a format where I could copy it directly to something like curl and make a request with. I also would like it to be human-readable unlike something like RequestBodyAsHTMLEncode. I know there is an export to curl function but I would like to use it for other things as well so I need this functionality.

**Comment by hemantsharma-io** [comment]
> I would like to have the body in a format where I could copy it directly to something like curl and make a request with. I also would like it to be human-readable unlike something like RequestBodyAsHTMLEncode. I know there is an export to curl function but I would like to use it for other things as well so I need this functionality.

The Session object has a method GetResponseBodyAsString or GetRequestBodyAsString which can be used like below:
```
{{#SelectedSessions}}
   {{{GetRequestBodyAsString}}}
{{/SelectedSessions}}
```
Note that i've used {{{ }}} (i.e. 3 braces) to get request body without HTML encoding. if I use {{GetRequestBodyAsString}} i.e. 2 braces then the value will be by default HTML Encoded.

if you are interested in more properties and method then you can go to **_Fiddler > Rules > Customize Rules_** which should open the Fiddler Script editor and on right side you can see the session object with all the possible properties and methods that you can use:
![image](https://user-images.githubusercontent.com/24278345/112732920-d818c100-8f62-11eb-84b9-a8ee243bd865.png)

![image](https://user-images.githubusercontent.com/24278345/112733022-815fb700-8f63-11eb-9cd4-49b571e92107.png)

**Comment by hemantsharma-io** [comment]
i've also added a most used variables section to the wiki
[https://github.com/hemantsharma-io/MockingBird#most-used-variables](https://github.com/hemantsharma-io/MockingBird#most-used-variables)
