### ISSUE TITLE
MockingBird tab not showing in fiddler v5.0.20192.25091 for .NET 4.6.1

### ISSUE THREAD

**Issue by jaypan13** [hemantsharma-io/MockingBird#6]
Hi Hemant, The tab is not showing in fiddler v5.0.20192.25091 for .NET 4.6.1. The fiddler is installed here - C:\Users\<user>\AppData\Local\Programs\Fiddler and I have put the dll and it's corresponding templates in Scripts folder underneath it. In the loaded extensions it shows - MockingBird.Core.ExtensionLoader (v1.0.0.0)	from %USERPROFILE%\AppData\Local\Programs\Fiddler\Scripts\MockingBird.dll. It doesn't show tab.

**Comment by hemantsharma-io** [comment]
@Jay1305 - if you switch to Log tab you should see any error occurred while loading the extension. Check that and let me know

**Comment by jaypan13** [comment]
Hi @hemantsharma-io, thank you. I didn't notice that in logs. I can see that the addon is looking for path "C:\Users\<user>\AppData\Local\Programs\Fiddler\Scripts\templates instead of that is mentioned in the Readme.md (https://github.com/hemantsharma-io/MockingBird/blob/master/README.md) which says - "C:\Users\<user>\AppData\Local\Programs\Fiddler\Scripts\MockingBirdTemplates. I changed the directory name to templates instead of MockingBirdTemplates and it has started showing the tab.

**Comment by hemantsharma-io** [comment]
Thanks a lot for highliting the issue in README. I've fixed it now.
