### ISSUE TITLE
Is there any document listing all of the available parameters that can be used in the template?

### ISSUE THREAD

**Issue by ElliotMok** [hemantsharma-io/MockingBird#7]
I can only know that parameters such as "RequestMethod", "RequestHeaders", "fullUrl", "RequestBodyAsBase64" inferred from the example templates are available,  but how can I get all of the other available parameters?

**Comment by hemantsharma-io** [comment]
![Fiddler-Properties](https://user-images.githubusercontent.com/24278345/72680239-929a7180-3add-11ea-942e-4f29325496d5.png)
There is no documentation as such as almost all the parameters being used are from Fiddler's objects' properties only e.g. typically Session as this is a particular HTTP transaction. To explore you can Fiddler > Fiddler Script (tab)  > 'Class View' (button click). This will show you all the properties/parameters available for use. I've also attached the screenshot to help.

Let me know if this solves the issue!

**Comment by hemantsharma-io** [comment]
I m closing this issue

**Comment by FrenziedIM** [comment]
Hi @hemantsharma-io, love your extension here! For HttpWebRequest (C#), we cannot do request.Headers.Add("Connection", "keep-alive"), we have to add it as a boolean (request.KeepAlive = true). Does fiddler have any boolean parameter/variable dictating whether a request has keep alive or not?

Cheers!
