### ISSUE TITLE
I do not see the extension in fiddler

### ISSUE THREAD

**Issue by bikotoru** [hemantsharma-io/MockingBird#8]
I have a fiddler 5.0.20194.41348 for .Net 4.6.1

![image](https://user-images.githubusercontent.com/6192404/79786503-8f4c9700-8313-11ea-9053-6ec38fb1810f.png)
And the extension does not appear to me
![image](https://user-images.githubusercontent.com/6192404/79786529-9c698600-8313-11ea-9341-4dd85fab8c4c.png)

And if I go to extensions if you recognize it

![image](https://user-images.githubusercontent.com/6192404/79786559-a8554800-8313-11ea-8aaa-124bddfc3787.png)

**Comment by hemantsharma-io** [comment]
sorry for the late response what do you see in 'Log' tab

**Comment by hemantsharma-io** [comment]
As long as you have fiddler extension and the template folder in the Scripts folder it should work. You should be able to diagnose the problem if you look at 'Log' tab. Fiddler logs everything here.
